version: '3.8'

services:
  frontend:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DB_HOST: db
      - DB_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: mysecretpassword
      - POSTGRES_DB: bakery
    ports:
      - "5432:5432"
